# Generated by Django 5.1.5 on 2025-12-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('district', 'District Administration'), ('municipal', 'Municipal Corporation'), ('ward', 'Ward Committee')], max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('ward_number', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='govgraph.department')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.IntegerField(help_text='Escalation ladder position (1=lowest)')),
                ('responsibilities', models.JSONField(default=list, help_text='List of responsibilities')),
                ('typical_response_time', models.IntegerField(blank=True, help_text='Expected response time in hours', null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='govgraph.department')),
            ],
            options={
                'ordering': ['department', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_address', models.TextField(blank=True)),
                ('verified_by_users', models.IntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('appointed_on', models.DateField(blank=True, null=True)),
                ('tenure_ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='govgraph.designation')),
            ],
            options={
                'ordering': ['-is_active', '-verified_by_users'],
            },
        ),
        migrations.CreateModel(
            name='ContactVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='govgraph.officer')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['state', 'district', 'city'], name='govgraph_de_state_c2ee2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('department', 'title')},
        ),
    ]
