FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY apps/web/package*.json ./

# Install dependencies
RUN npm ci

# Copy application
COPY apps/web /app

EXPOSE 3000

CMD ["npm", "run", "dev"]
