# Generated by Django 5.1.5 on 2025-12-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('problem_keywords', models.JSONField(default=list, help_text='Keywords for semantic search')),
                ('steps', models.JSONField(default=list, help_text='Ordered list of action steps')),
                ('success_rate', models.FloatField(default=0.0, help_text='Percentage of users who found this helpful')),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='wiki.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-success_rate', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_taken', models.JSONField(help_text='Actual steps the user followed')),
                ('outcome', models.TextField()),
                ('time_to_resolve', models.IntegerField(help_text='Days taken to resolve')),
                ('evidence_urls', models.JSONField(default=list, help_text='Links to photos/documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_paths', to='wiki.solution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('rti', 'RTI Application'), ('complaint', 'Formal Complaint'), ('appeal', 'First Appeal'), ('letter', 'Official Letter')], max_length=20)),
                ('content', models.TextField(help_text='Template with {{placeholders}}')),
                ('language', models.CharField(default='en', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='wiki.category')),
            ],
            options={
                'ordering': ['template_type', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['language', 'category'], name='wiki_soluti_languag_5790e1_idx'),
        ),
    ]
