# Generated by Django 5.1.5 on 2025-12-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
