# Generated by Django 5.1.5 on 2025-12-31 21:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_solutionsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geolocation of the solution scope', null=True, srid=4326),
        ),
    ]
