# Generated by Django 5.1.5 on 2025-12-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_downvotes'),
        ('wiki', '0004_solution_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='related_issues',
            field=models.ManyToManyField(blank=True, help_text='Issues solved by this solution', related_name='solutions', to='issues.issue'),
        ),
    ]
