# Generated by Django 5.1.5 on 2025-12-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
